### ISSUE TITLE
Advice on using docker-silk container?

### ISSUE THREAD

**Issue by richb-hanover** [redjack/docker-silk#6]
Thanks for building this skeleton. For us newcomers to Docker, it would help if there were a few words about how to start SiLK on this container, and how to send netflow/etc data to it. Thanks again!

**Comment by richb-hanover** [comment]
@rouge8  - any advice on configuring/starting up this container? Thanks!

**Comment by rouge8** [comment]
I haven't used it recently, but I always used it on existing netflow files collected elsewhere by mounting a directory on the host as a data volume: https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-directory-as-a-data-volume

**Comment by richb-hanover** [comment]
Ahah! And have you ever used it to receive netflow packets (say, on port 2055)? Thanks.

**Comment by rouge8** [comment]
I never did, sorry! I suspect you'd want to mount a directory on the host to store the data and `-p` to expose a port: https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose

**Comment by richb-hanover** [comment]
OK. It's useful to understand that I have a different use case. I know about the -p option in Docker, but I'll have to bone up on it. I think the SiLK installation docs are pretty clear on what has to happen, so I'll hew pretty closely to those. Thanks again.
